//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomRnD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM_BomTHLK
    {
        public int Id { get; set; }
        public string MaTpModul { get; set; }
        public string MaTp { get; set; }
        public string ThiTruong { get; set; }
        public string MaBtp { get; set; }
        public string MaBtpPhu { get; set; }
        public Nullable<int> HeSo { get; set; }
        public string GhiChu { get; set; }
        public string UserName { get; set; }
        public string UserNameEdit { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
    
        public virtual BOM_BomBtp BOM_BomBtp { get; set; }
        public virtual BOM_BomBtp BOM_BomBtp1 { get; set; }
        public virtual BOM_BomTp BOM_BomTp { get; set; }
        public virtual BOM_BomTp BOM_BomTp1 { get; set; }
    }
}
